name: Main Multi-Workflow Controller

on:
  push:
    branches:
      - main

jobs:
  # Deploys the bookmarklet install page to GitHub Pages
  run-static-site:
    uses: ./.github/workflows/static.yml
