name: Deploy Static Site

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Granting necessary permissions for GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './bookmarklet'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
